### ISSUE TITLE
Error: DiscordAPIError: Unknown Webhook

### ISSUE THREAD

**Issue by PenT1x** [Rahuletto/simply-djs#54]
**Describe the bug**
I get this error when I use embedPages:
Error Occured. | embedPages | Error: DiscordAPIError: Unknown Webhook
    at RequestHandler.execute (E:\VerPixia\Xatis\node_modules\discord.js\src\rest\RequestHandler.js:349:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (E:\VerPixia\Xatis\node_modules\discord.js\src\rest\RequestHandler.js:50:14)
    at async InteractionWebhook.send (E:\VerPixia\Xatis\node_modules\discord.js\src\structures\Webhook.js:192:15)
    at async Object.embedPages (E:\VerPixia\Xatis\node_modules\simply-djs\src\embedPages.js:129:5)

**To Reproduce**
I do not know what I do wrong, but this is my code:
simplydjs.embedPages(client, interaction, pages, {
    pgCount: true,
    skipBtn: true,
    delBtn: true
})

**Expected behavior**
That it works

**Versions (please complete the following information):**
 - Discord.js Version [e.g. v13] 13.3.1
 - simply-djs Version [e.g. v2.0.0] 2.5.2

**Comment by Rahuletto** [comment]
Unknown webhook usually occurs when u reply soo late/slow. This may occur due the the bot ping.

We will try to reduce as much errors as possible 🥲
